knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 120
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:
            lowquality: false
            encoding: UTF-8
            #page-size: LETTER
            no-outline: true
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
