vich_uploader:
    db_driver: orm

    mappings:
        image_user:
            uri_prefix: '%app.path.users%'
            upload_destination: '%kernel.project_dir%/public/%app.path.users%'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: {property: 'id'}
        image_store:
            uri_prefix: '%app.path.store%'
            upload_destination: '%kernel.project_dir%/public/%app.path.store%'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
        image_product:
            uri_prefix: '%app.path.product%'
            upload_destination: '%kernel.project_dir%/public/%app.path.product%'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: {property: 'id'}
