# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    container.dumper.inline_factories: true

    locale: "fr"
    setting: '%env(resolve:DATABASE_URL)%'
    upload_dir: 'uploads/files/'
    app.path.users: 'uploads/images/users'
    app.path.images: 'dist/images'
    app.path.store: 'dist/images/logo'
    app.path.product: 'uploads/images/products'
    app.code_send: '%env(resolve:APP_CODE)%'
    app.mode: '%env(resolve:MODE)%'

    app.database.username: '%env(resolve:DB_USERNAME)%'
    app.database.password: '%env(resolve:DB_PASSWORD)%'
    app.database.db: '%env(resolve:DB_DATABASE)%'
    app.database.port: '%env(resolve:DB_PORT)%'
    app.database.host: '%env(resolve:DB_HOST)%'
    app.database.backupdir: '%kernel.project_dir%/db/'
    app.translationdir: '%kernel.project_dir%/translations/'
    app.temptranslationdir: '%kernel.project_dir%/tempTrans/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Suscriber\LocalChangeSubscriber:
        arguments:
            $defaultLocale: '%locale%'